REC-3916 zoom speed corresponding to movement speed
chax-at/camera-preview pull request #3
Opened 2024-04-18 11:22 UTC by s4ndr4h

2024-04-18 11:42 UTC, powerpaul17 commented on android/src/main/java/com/ahm/capacitor/camera/preview/CameraActivity.java
> +                            zoomDifference = Math.max(Math.round(distDifference / zoomFactor), minimumZoomStep);
Ist `minimumZoomStep` nicht eigentlich ein `maximumNegativeZoomStep`? :wink:

2024-04-19 07:14 UTC, s4ndr4h commented on android/src/main/java/com/ahm/capacitor/camera/preview/CameraActivity.java
> +                            zoomDifference = Math.max(Math.round(distDifference / zoomFactor), minimumZoomStep);
Stimmt, die Variable ist evtl. überflüssig :)

2024-04-22 08:27 UTC, JMuratha requested changes

2024-04-22 08:27 UTC, JMuratha commented on android/src/main/java/com/ahm/capacitor/camera/preview/CameraActivity.java
> +                                        if (action == MotionEvent.ACTION_DOWN) {
Was ist das Event Action Down?
Ist das, wenn ich mit einem Finger den Bildschirm berühre?

Wenn ja, dann passt da was mit deinem Reset Code nicht:
Wenn jemand mit beiden Fingern den Bildschirm gleichzeitig berührt, dass das hier nie ausgeführt wird (weil der `eventCount` direkt von 0 auf 2 geht).

Ich kann mir vorstellen, dass das gleichzeitig draufklicken leicht passieren kann, wenn das System gerade ausgelastet ist und der User das Recht gleichzeitig macht. Da ist halt die Frage wie das Eventhandling damit umgeht

2024-04-22 08:41 UTC, s4ndr4h commented on android/src/main/java/com/ahm/capacitor/camera/preview/CameraActivity.java
> +                                        if (action == MotionEvent.ACTION_DOWN) {
Genau das Event wird getriggert wenn man den Bildschirm berührt. Bei den Tests hatte ich eigentlich nie den Fall, dass `ACTION_DOWN` im ersten Teil von dem if-else-statement ausgeführt wurde. Aber es ist auch kein Problem den Reset ausserhalb davon zu machen. Dann wird es sicher ausgeführt.

2024-04-23 05:27 UTC, JMuratha approved these changes

2024-04-23 09:15 UTC, merged